'use strict';
/* Fast config check: summarize a resolved config and lint scene bodies.
 * No TTS, no browser, no writes — resolveConfig has already thrown on hard
 * errors, so everything here is a warning (exit stays 0).
 *
 * Modes (second argument to check()):
 *   check(config)          — default: warnings only, exit 0
 *   check(config, {strict:true})  — stricter validation, still exit 0
 *   check(config, {release:true}) — all checks, errors fail the build (exit 1)
 *
 * Release mode elevates: remote assets, unresolved references, unsupported HTML,
 * missing claims, black frames, and remote dependencies from warnings to errors. */
const fs = require('fs');
const path = require('path');
const { PLATFORMS } = require('./util');
const { captureStatus } = require('./walkthrough');

/* Factual-claim sniffing for the grounding rule (references/url-to-source.md
 * §Claims ledger): a stat or superlative in the voiceover must be traceable to
 * the source. Heuristic — warnings only, never errors. */
const CLAIM_PATTERNS = [
  /\d[\d,.]*\s*(?:%|percent\b|x\b|\+|k\b|million\b|billion\b|users?\b|products?\b|customers?\b|downloads?\b|countries\b)/i,
  /\b(?:leading|best[- ]in[- ]class|industry[- ]first|world'?s first|largest|most popular|#1|number one|top-rated|half of)\b/i,
];

function findClaims(config) {
  const hits = [];
  for (const s of config.scenes) {
    s.vo.forEach((t, j) => {
      if (CLAIM_PATTERNS.some(re => re.test(t.text))) {
        hits.push({ ref: `scene "${s.id}" turn ${j}: "${t.text.length > 90 ? t.text.slice(0, 87) + '\u2026' : t.text}"`, text: t.text });
      }
    });
  }
  return hits;
}

/* Parse a claims.md ledger into an array of claim-text lines for matching.
 * Supports three formats:
 *   1. ## claim: ... headings
 *   2. Bullet lines beneath claim headings
 *   3. Markdown table rows under ## Claims (the format generated by `narova ingest`) */
function readClaimsLedger(config) {
  const dir = config.projectDir || '.';
  for (const name of ['claims.md', 'CLAIMS.md']) {
    const p = path.join(dir, name);
    if (fs.existsSync(p)) {
      const text = fs.readFileSync(p, 'utf8');
      const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
      const claimLines = [];
      let inClaimsTable = false;
      for (const l of lines) {
        if (l.startsWith('## claim:') || l.startsWith('## Claim:')) {
          inClaimsTable = false;
          claimLines.push(l.replace(/^##\s*claim:\s*/i, '').trim());
        } else if (l === '## Claims' || /^##\s+Claims/i.test(l)) {
          inClaimsTable = true;
        } else if (inClaimsTable && /^\|[-|\s]+\|$/.test(l)) {
          // Separator row (e.g. |---|---|) — skip.
          continue;
        } else if (inClaimsTable && l.startsWith('|')) {
          // Table row: extract the second column (claim text).
          const cols = l.split('|').map(c => c.trim()).filter(Boolean);
          if (cols.length >= 2) {
            const claimCol = cols[1];
            if (claimCol.length > 4) claimLines.push(claimCol);
          }
        } else if (!inClaimsTable && l.startsWith('- ') && claimLines.length) {
          const bullet = l.replace(/^-\s+/, '');
          if (bullet.length > 4) claimLines.push(bullet);
        }
      }
      return { path: p, claims: claimLines };
    }
  }
  return null;
}

/* Check if a vo claim is ledgered. It matches when the claim text (or a
 * significant substring of it) appears somewhere in the ledger lines. */
function matchClaim(claimText, ledger) {
  if (!ledger || !ledger.claims.length) return false;
  const needle = claimText.toLowerCase();
  // Also try a shorter digest: drop leading punctuation/stopwords for a
  // looser match.
  const short = needle.replace(/^[^a-z0-9]*/, '').slice(0, 40);
  return ledger.claims.some(entry => {
    const hay = entry.toLowerCase();
    return hay.includes(needle.slice(0, 60)) || hay.includes(short);
  });
}

/* Release-mode checks that are too slow or pedantic for normal `check`. */
function releaseChecks(config, errors) {
  for (const s of config.scenes) {
    // Black-frame / empty scene: body with no visible text, images, videos, or SVG.
    const body = String(s.body);
    const hasText = body.replace(/<!--[\s\S]*?-->/g, '').replace(/<[^>]*>/g, '').trim().length > 0;
    const hasVisual = /<(?:img|video|svg|path|circle|rect|ellipse|polygon|line|use)\b/i.test(body);
    const hasVisibleWalkthrough = s.walkthrough && s.walkthrough.opacity !== 0;
    if (!hasText && !hasVisual && !s.clip && !hasVisibleWalkthrough) {
      errors.push(`scene "${s.id}": body has no visible content and no b-roll or walkthrough media — scene will render as a black frame`);
    }

    // Remote dependencies in body HTML.
    for (const t of tags(body)) {
      const tagName = t.match(/^<(\w+)/);
      if (tagName && ['script', 'link', 'iframe'].includes(tagName[1].toLowerCase())) {
        errors.push(`scene "${s.id}": contains a <${tagName[1]}> element — remote dependencies are not supported during render`);
      }
    }

    // Unsupported HTML patterns that HyperFrames cannot render.
    if (/<(?:canvas|web-component|marquee|blink)\b/i.test(body)) {
      errors.push(`scene "${s.id}": contains an unsupported HTML element (<canvas>, <web-component>) — HyperFrames may not render it deterministically`);
    }
  }

  // Remote url() references in theme.css.
  for (const ref of cssUrls(config.themeCss || '')) {
    if (/^(?:https?:)?\/\//i.test(ref)) {
      errors.push(`theme.css: remote url() "${ref}" — download the asset into project assets/ before rendering`);
    }
  }
}

/* All opening tags in a body, with HTML comments stripped first — attributes
 * are only linted inside tags, never in visible prose. */
function tags(body) {
  return String(body).replace(/<!--[\s\S]*?-->/g, '').match(/<[a-zA-Z][^>]*>/g) || [];
}

function attr(tag, name) {
  const m = new RegExp(`(?<![-\\w])${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>"']+))`).exec(tag);
  return m ? (m[1] ?? m[2] ?? m[3]) : undefined;
}

function cssUrls(css) {
  const refs = [];
  const re = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)'"\s]+))\s*\)/gi;
  let m;
  while ((m = re.exec(String(css))) !== null) refs.push(m[1] ?? m[2] ?? m[3]);
  return refs;
}

function inspectAssetRef(ref, config, at, warnings, opts = {}) {
  const release = !!opts.release;
  const errors = opts._errors || null;  // release mode: push failures here instead
  if (!ref || /^(?:data:|blob:|#|mailto:|tel:)/i.test(ref)) return;
  if (/^(?:https?:)?\/\//i.test(ref)) {
    if (release && errors) {
      errors.push(`remote asset: "${ref}" — download it into project assets/ before rendering (${at})`);
    } else {
      warnings.push(`${at}: remote asset "${ref}" — download it into project assets/ before rendering`);
    }
    return;
  }
  if (!ref.startsWith('assets/')) {
    if (release && errors) errors.push(`${at}: local asset "${ref}" must live under project assets/ and be referenced as assets/...`);
    else warnings.push(`${at}: local asset "${ref}" must live under project assets/ and be referenced as assets/...`);
    return;
  }
  if (!config.assetsDir) {
    if (release && errors) errors.push(`${at}: "${ref}" is referenced but the project has no assets directory`);
    else warnings.push(`${at}: "${ref}" is referenced but the project has no assets directory`);
    return;
  }
  const relative = ref.slice('assets/'.length).split(/[?#]/, 1)[0];
  const target = path.resolve(config.assetsDir, relative);
  const boundary = path.relative(config.assetsDir, target);
  if (!relative || boundary === '..' || boundary.startsWith(`..${path.sep}`) || path.isAbsolute(boundary)) {
    if (release && errors) errors.push(`${at}: asset path "${ref}" escapes project assets/`);
    else warnings.push(`${at}: asset path "${ref}" escapes project assets/`);
  } else if (!fs.existsSync(target)) {
    if (release && errors) errors.push(`${at}: asset not found: ${ref}`);
    else warnings.push(`${at}: asset not found: ${ref}`);
  }
}

/* Rough narration-length estimate so a target duration ("about 2 minutes") can
 * be tuned BEFORE synth: piper at ~1.1–1.2 tempo speaks near 170 wpm base
 * (calibrated against real builds; 647 words at 1.12 ≈ 231s actual), scaled
 * by tempo (matching the narova_tts default of 1.18 when unset), plus the
 * fixed per-turn/scene gaps the pipeline inserts. Word timing is computed,
 * not measured — this is a planning number, not a promise. */
function estimateSeconds(config) {
  const timing = config.timing || {};
  const tempo = timing.tempo || 1.18;
  const wps = (170 * tempo) / 60;
  const lead = timing.lead ?? 0.16, tail = timing.tail ?? 0.58;
  const gapS = timing.gapSentence ?? 0.24, gapT = timing.gapTurn ?? 0.44;
  let total = 0;
  for (const s of config.scenes) {
    total += lead + tail;
    s.vo.forEach((t, i) => {
      total += t.text.trim().split(/\s+/).length / wps + gapS + (i ? gapT : 0);
    });
  }

  return total;
}

function fmtDuration(sec) {
  const s = Math.round(sec);
  return s >= 60 ? `${Math.floor(s / 60)}m${String(s % 60).padStart(2, '0')}s` : `${s}s`;
}

/* Scene transition kinds (compose/runtime.js): anything else falls back to
 * fade at runtime — warn here so the fallback is never a surprise. */
const SCENE_TRANSITIONS = new Set(['fade', 'wipe', 'slide', 'zoom']);

/* data-mark annotation kinds (compose/runtime.js): the runtime IGNORES any
 * other value, so an unknown kind is a warning, mirroring the runtime set
 * exactly. */
const MARK_KINDS = new Set(['underline', 'circle', 'box', 'highlight']);

/* HyperFrames-reserved class names — if used in body HTML they collide with
 * the generated composition structure and silently break layout. */
const HF_RESERVED_CLASSES = new Set([
  'scene', 'clip', 'chrome', 'overlay', 'canvas', 'scenebody', 'capzone',
  'progress', 'topbar', 'wordmark', 'counter', 'cap-stage', 'cap-group',
  'spk', 'cap-w', 'caption2', 'marklayer', 'walkthrough-media',
  'walkthrough-shell', 'walkthrough-titlebar', 'walkthrough-dots',
  'has-walkthrough', 'walkthrough-window', 'walkthrough-full',
]);

/* Hook enforcement (§Hook doctrine in the skill references).
 * Viral video mechanics in 2026: muted autoplay is 80%+, hooks are measured at
 * 2s, the first syllable must land within ~200ms. Scene 1 is the hook. */
function checkHook(config, warnings) {
  const s1 = config.scenes[0];
  if (!s1) return;

  const timing = config.timing || {};

  // 1 — lead-in silence > 200ms (dead air at the head loses viewers in <2s).
  const lead = timing.lead ?? 0.16;
  if (lead > 0.2) {
    warnings.push(`hook: timing.lead is ${lead}s (>200ms) — the first syllable should land within 200ms; set "timing.lead" ≤ 0.2`);
  }

  // 2 — no visible text on-screen for muted viewers.
  const body = String(s1.body);
  const textEls = body.match(/<(?:h[1-6]|p|span|div|a|li|label|figcaption|blockquote)\b[^>]*>[^<]+<\/(?:h[1-6]|p|span|div|a|li|label|figcaption|blockquote)>/gi);
  if (!textEls || textEls.length === 0) {
    warnings.push(s1.walkthrough
      ? 'hook: scene 1 shows the product but has no on-screen hook text — add a short claim so muted viewers know why the action matters'
      : 'hook: scene 1 has no visible text — muted viewers (80%+ of autoplay) see a blank screen; add hook text on-screen');
  }

  // 3 — platform duration band already checked (see check() below).

  // 4 — last scene has no saveable end-frame (no text, no image, no CTA).
  const last = config.scenes[config.scenes.length - 1];
  const lastBody = String(last.body);
  const hasImage = /<(?:img|svg|video)\b/i.test(lastBody);
  const lastTextEls = lastBody.match(/<(?:h[1-6]|p|span|div|a|li|label|figcaption|blockquote)\b[^>]*>[^<]+<\/(?:h[1-6]|p|span|div|a|li|label|figcaption|blockquote)>/gi);
  if (!hasImage && (!lastTextEls || lastTextEls.length === 0)) {
    warnings.push(`saveable: last scene "${last.id}" has no text or image — a saveable end-card lifts completion rate; add a title, logo, or CTA`);
  }
}

/* Print warnings + a one-line summary. Returns true (warnings never fail).
 * Cue semantics (compose/runtime.js): data-cue="k" is coerced with +k and
 * looked up in turns[] (0-based) when it is a non-negative integer in range;
 * anything else falls back to scene entry. Mirror that coercion exactly —
 * never warn about a spelling the runtime resolves. */
function check(config, opts = {}) {
  const warnings = [];
  const errors = [];
  const release = !!opts.release;
  const strict = release || !!opts.strict;
  const bodyIds = new Set();

  const issue = (msg) => release ? errors.push(msg) : warnings.push(msg);
  const releaseIssue = (msg) => errors.push(msg);

  for (const s of config.scenes) {
    const sceneIds = new Set();
    if (s.transition != null && !SCENE_TRANSITIONS.has(s.transition)) {
      warnings.push(`scene "${s.id}": unknown transition "${s.transition}" (valid: fade, wipe, slide, zoom) — the runtime falls back to fade`);
    }
    if (s.transition === 'wipe' && estimateSeconds(config) > 30) {
      warnings.push(`scene "${s.id}": "wipe" transition uses clip-path, which forces screenshot capture on all frames — consider "fade" for faster renders on videos over 30s`);
    }
    for (const t of tags(s.body)) {
      for (const name of ['src', 'poster']) {
        const ref = attr(t, name);
        if (ref != null) inspectAssetRef(ref, config, `scene "${s.id}" ${name}`, warnings, { release, _errors: errors });
      }
      const href = attr(t, 'href');
      if (/^(?:https?:)?\/\//i.test(href || '') || /^assets\//.test(href || '')) {
        inspectAssetRef(href, config, `scene "${s.id}" href`, warnings, { release, _errors: errors });
      }
      // cues
      if (/(?<![-\w])data-cue\s*=/.test(t)) {
        const raw = attr(t, 'data-cue');
        const k = +raw;
        if (!Number.isInteger(k) || k < 0) {
          warnings.push(`scene "${s.id}": data-cue="${raw}" does not resolve to a turn — it reveals at scene entry`);
        } else if (k >= s.vo.length) {
          warnings.push(`scene "${s.id}": data-cue="${raw}" but turns are indexed 0..${s.vo.length - 1} — it reveals at scene entry`);
        }
      } else if (/class\s*=\s*["'][^"']*\bcue\b/.test(t)) {
        warnings.push(`scene "${s.id}": class="cue" without data-cue — it animates at scene entry, not on a turn`);
      }
      if (/(?<![-\w])data-drift\s*=/.test(t) &&
          (/(?<![-\w])data-cue\s*=/.test(t) || /class\s*=\s*["'][^"']*\b(?:reveal|cue)\b/.test(t))) {
        warnings.push(`scene "${s.id}": data-drift="${attr(t, 'data-drift')}" on the same element as .reveal/.cue — both drive transform and fight; move the reveal/cue to a wrapper`);
      }
      const delay = attr(t, 'data-delay');
      if (delay != null && !Number.isFinite(+delay)) {
        warnings.push(`scene "${s.id}": data-delay="${delay}" is not a number of seconds`);
      }
      const count = attr(t, 'data-count');
      if (count != null && !Number.isFinite(parseFloat(count))) {
        warnings.push(`scene "${s.id}": data-count="${count}" is not numeric — the runtime skips it`);
      }
      if (/(?<![-\w])data-mark\s*=/.test(t)) {
        const kind = attr(t, 'data-mark');
        if (!MARK_KINDS.has(kind)) {
          warnings.push(`scene "${s.id}": data-mark="${kind}" is not a known mark (valid: underline, circle, box, highlight) — the runtime ignores it`);
        }
      }
      const classVal = attr(t, 'class');
      if (classVal) {
        const names = classVal.split(/\s+/);
        const hits = names.filter(n => HF_RESERVED_CLASSES.has(n));
        if (hits.length) {
          warnings.push(`scene "${s.id}": class="${classVal}" uses HyperFrames-reserved name${hits.length > 1 ? 's' : ''} ${hits.map(c => `"${c}"`).join(', ')} — rename to avoid silent layout breakage`);
        }
      }
      const id = attr(t, 'id');
      if (id != null) {
        bodyIds.add(id);
        if (sceneIds.has(id)) {
          warnings.push(`scene "${s.id}": duplicate id "${id}" within the scene — its url(#…) / href="#…" references become ambiguous`);
        } else sceneIds.add(id);
      }
    }
    for (const ref of cssUrls(s.body)) {
      inspectAssetRef(ref, config, `scene "${s.id}" inline style`, warnings, { release, _errors: errors });
    }

    if (s.clip) {
      const ext = path.extname(s.clip).toLowerCase();
      if (!['.mp4', '.webm', '.mov'].includes(ext)) {
        warnings.push(`scene "${s.id}": clip "${s.clip}" has unusual extension ${ext} — HyperFrames supports .mp4, .webm, .mov`);
      }
    }
  }

  const timingsPath = path.join(opts.outDir || path.join(config.projectDir || '.', 'out'), 'timings.json');
  let timings = null;
  if (fs.existsSync(timingsPath)) {
    try { timings = JSON.parse(fs.readFileSync(timingsPath, 'utf8')); } catch { /* synth will report malformed timings */ }
  }
  for (const [id, flow] of Object.entries(config.walkthroughs || {})) {
    const status = captureStatus(config, id, timings, {
      outDir: opts.outDir || path.join(config.projectDir || '.', 'out'),
    });
    if (!status.ok) {
      issue(`walkthrough "${id}": ${status.reason} — run \`narova walkthrough capture ${id}\` after synth`);
    }
    if (flow.mutates) {
      warnings.push(`walkthrough "${id}" declares mutating actions — capture against disposable demo data, never a production account`);
    }
  }

  // theme.css
  if (/animation[^;{}]*\binfinite\b/.test(config.themeCss || '')) {
    issue('theme.css uses "animation: … infinite" — not deterministic under frame rendering; move motion to data-cue/.reveal or drop it');
  }
  // Check for HyperFrames-reserved class names used as CSS selectors in theme.css.
  for (const klass of HF_RESERVED_CLASSES) {
    const re = new RegExp('\\.' + klass.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '(?![\\w-])', 'g');
    const matches = (config.themeCss || '').match(re);
    if (matches && matches.length) {
      warnings.push(`theme.css uses reserved class name "${klass}" as a selector — this may collide with generated composition classes`);
    }
  }
  if (/(?:font-family|--[\w-]*(?:font|serif|sans|mono))\s*:[^;{}]*(?:Georgia|Times New Roman|Arial|Roboto)/i.test(config.themeCss || '')) {
    warnings.push('theme.css uses a named fallback font — HyperFrames may fetch it; use the bundled family plus serif/sans-serif/monospace unless the extra family is intentional');
  }

  const SLOW_PATH_RULES = [
    { pattern: /\bbackdrop-filter\s*:/gi,  desc: 'backdrop-filter forces screenshot capture for every frame' },
    { pattern: /\bfilter\s*:\s*blur\b/gi,  desc: 'filter: blur() forces screenshot capture' },
    { pattern: /\bfilter\s*:\s*drop-shadow\b/gi,  desc: 'filter: drop-shadow() forces screenshot capture' },
    { pattern: /\bfilter\s*:\s*(?:brightness|saturate|contrast)\(/gi,  desc: 'filter: brightness/saturate/contrast() forces screenshot capture; use opacity instead' },
    { pattern: /\bmix-blend-mode\s*:/gi,   desc: 'mix-blend-mode is incompatible with the render capture path' },
  ];
  for (const rule of SLOW_PATH_RULES) {
    if (rule.pattern.test(config.themeCss || '')) {
      warnings.push(`theme.css: ${rule.desc} — remove the property or accept significantly slower renders`);
    }
  }
  for (const s of config.scenes) {
    if (!s.body) continue;
    for (const rule of SLOW_PATH_RULES) {
      if (rule.pattern.test(s.body)) {
        warnings.push(`scene "${s.id}" body: ${rule.desc} — move the effect to a plain color/opacity treatment in theme.css`);
      }
    }
  }
  for (const ref of cssUrls(config.themeCss || '')) {
    inspectAssetRef(ref, config, 'theme.css', warnings, { release, _errors: errors });
  }
  for (const id of bodyIds) {
    if (new RegExp(`#${id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![-\\w])`).test(config.themeCss || '')) {
      warnings.push(`theme.css targets #${id}, but compose renames body ids to <scene>--${id} — use a class selector instead`);
    }
  }

  // Platform duration band
  if (config.platform && PLATFORMS[config.platform]) {
    const [lo, hi] = PLATFORMS[config.platform].band;
    const estSec = estimateSeconds(config);
    if (estSec < lo) {
      warnings.push(`platform ${config.platform} targets ${lo}–${hi}s; estimated narration is ${Math.round(estSec)}s — add material or pick a shorter format`);
    } else if (estSec > hi) {
      const band = lo > 0 ? `targets ${lo}–${hi}s` : `allows up to ${hi}s`;
      warnings.push(`platform ${config.platform} ${band}; estimated narration is ${Math.round(estSec)}s — tighten the script or pick a longer format`);
    }
  }

  // Hook doctrine
  // Only check hooks when using TTS narration (external narration has its own pacing).
  if (!config.narrationSource || !config.narrationSource.file) {
    checkHook(config, warnings);
  }

  // ---- Strict / Release ----

  // Claims ledger: in strict mode, warn on unledgered claims.
  // In release mode, error on unledgered claims.
  const claims = findClaims(config);
  if (claims.length) {
    if (strict) {
      const ledger = readClaimsLedger(config);
      if (!ledger) {
        releaseIssue(
          `vo contains ${claims.length} factual claim${claims.length === 1 ? '' : 's'} but the project has no claims.md ledger — ` +
          'tag each verbatim/paraphrase/inference against the source before synth (references/url-to-source.md):',
        );
        for (const c of claims.slice(0, 5)) releaseIssue(`  ${c.ref}`);
      } else {
        const unledgered = claims.filter(c => !matchClaim(c.text, ledger));
        if (unledgered.length) {
          const msg = `${unledgered.length} of ${claims.length} claim${claims.length === 1 ? '' : 's'} not found in ${path.relative(config.projectDir || '.', ledger.path)}:`;
          if (release) {
            releaseIssue(msg);
            for (const c of unledgered.slice(0, 5)) releaseIssue(`  ${c.ref}`);
          } else {
            warnings.push(msg);
            for (const c of unledgered.slice(0, 5)) warnings.push(`  ${c.ref}`);
          }
        }
      }
    } else {
      // Non-strict: warn only if no ledger at all.
      const dir = config.projectDir || '.';
      const hasLedger = ['claims.md', 'CLAIMS.md'].some(f => fs.existsSync(path.join(dir, f)));
      if (!hasLedger) {
        warnings.push(
          `vo contains ${claims.length} factual claim${claims.length === 1 ? '' : 's'} but the project has no claims.md ledger — ` +
          'tag each verbatim/paraphrase/inference against the source before synth (references/url-to-source.md):',
          ...claims.slice(0, 5).map(c => `  ${c.ref}`),
        );
      }
    }
  }

  // Release-mode exclusive checks
  if (release) {
    releaseChecks(config, errors);
  }

  // Print
  for (const w of warnings) console.log(`warn: ${w}`);
  for (const e of errors) console.log(`${release ? 'fail' : 'warn'}: ${e}`);

  if (release) {
    if (errors.length) {
      console.log(`FAIL (release): ${errors.length} error${errors.length === 1 ? '' : 's'} — fix before building`);
    } else {
      console.log(`ok: release check passed — ${warnings.length} warning${warnings.length === 1 ? '' : 's'} (clean build gate)`);
    }
  }

  const turns = config.scenes.reduce((n, s) => n + s.vo.length, 0);
  const words = config.scenes.reduce((n, s) =>
    n + s.vo.reduce((m, t) => m + t.text.trim().split(/\s+/).length, 0), 0);
  const hasExternalNarration = !!(config.narrationSource && config.narrationSource.file);
  const backends = hasExternalNarration ? 'external'
    : [...new Set(Object.values(config.voices).map(v => v.backend))].join('+') || 'silent';
  const est = hasExternalNarration
    ? fmtDuration(config.scenes.reduce((n, s) => n + (s.dur || 0), 0))
    : fmtDuration(estimateSeconds(config));
  const tempo = (config.timing && config.timing.tempo) || 1.18;
  const walkthroughCount = Object.keys(config.walkthroughs || {}).length;
  const walkthroughSummary = walkthroughCount ? `, ${walkthroughCount} walkthrough${walkthroughCount === 1 ? '' : 's'}` : '';
  const karaokeNote = config.narrationSource?.wordTimings ? `, ${config.narrationSource.wordTimings.length} karaoke cues` : '';
  console.log(`ok: "${config.title}" — ${config.scenes.length} scenes, ${turns} turns${walkthroughSummary}${karaokeNote}, ~${words} words, ≈${est} narration (est. at tempo ${tempo}) (${config.size.w}x${config.size.h}, ${backends})`);

  return !(release && errors.length > 0);
}

module.exports = { check };
