'use strict';

const path = require('path');
const fs = require('fs');
const { compose, composeSceneProject } = require('../compose');
const { runHf, HYPERFRAMES_VERSION } = require('../hf');
const { materializeVisualBodies } = require('./visual');
const { which, ensureDir, sh } = require('../util');
const { sha256 } = require('../manifest');

const provider = {
  name: 'hyperframes',
  displayName: 'HyperFrames',
  providerVersion: HYPERFRAMES_VERSION,
  protocol: 'narova-renderer-provider/v1',
  local: true,
  browserless: false,
  capabilities: {
    html: true,
    portableVisuals: true,
    css: true,
    video: true,
    svg: true,
    captions: true,
    snapshots: true,
    studio: true,
  },

  /* Scene-level render cache. HyperFrames now supports per-scene rendering by
   * composing each scene as an independent HyperFrames project with the scene's
   * timeline rebased to t=0, a trimmed audio track, and a scene-local DATA
   * object. Dirty scenes re-render as their own projects; cached spans are
   * concatenated + muxed with the full audio track via ffmpeg. The
   * whole-video path remains as the fallback for any cache failure.
   *
   * `isolated: true` marks that this renderer's per-scene path RECOMPOSES a
   * standalone scene-local project (unlike no-browser, which renders the full
   * project at absolute frame times). Only isolated per-scene rendering is
   * subject to the selective-render safety gate in scene-cache.js, because
   * only it has to rebase authored behavior into a t=0 timeline. */
  cache: { mode: 'per-scene', isolated: true },

  doctor() {
    return {
      ok: !!which('npx'),
      checks: [
        { name: 'npx', ok: !!which('npx'), detail: which('npx') || 'not found' },
        { name: 'browser', ok: null, detail: 'downloaded/managed by HyperFrames when rendering' },
      ],
    };
  },

  compose(config, outDir) {
    return compose(materializeVisualBodies(config), outDir);
  },

  render(config, outDir, opts = {}) {
    const composed = this.compose(config, outDir);
    const name = opts.name || 'video.mp4';
    const args = ['render', '--output', path.join('..', name)];
    if (opts.videoFrameFormat) args.push('--video-frame-format', opts.videoFrameFormat);
    if (opts.fps) args.push('--fps', String(opts.fps));
    if (opts.quality) args.push('--quality', String(opts.quality));
    runHf(args, composed.dir);
    return { ...composed, mp4: path.join(outDir, name), project: composed.dir };
  },

  /* Render only the scene spans whose cache key changed. Each span gets its own
   * standalone HyperFrames project (generated by composeSceneProject) and is
   * rendered independently. After HF render, each span is re-encoded with
   * concat-safe parameters (setsar=1, no B-frames) and stripped of audio
   * (the full audio track is muxed at assembly time). */
  renderSpans(config, outDir, spans, opts = {}) {
    // Ensure the full project is composed first (assets, style.css, etc.)
    const composed = this.compose(config, outDir);
    const fps = Number(opts.fps || 30);
    for (const span of spans) {
      const sceneIdx = span.sceneIndex;
      const spanProject = composeSceneProject(config, outDir, sceneIdx);
      // HF render output goes to a temp file in the composed dir
      const hfOut = path.join(composed.dir, `_span-${span.cacheKey.slice(0, 8)}.mp4`);
      const args = ['render', '--output', path.join('..', '..', '..', path.relative(composed.dir, hfOut))];
      if (opts.quality) args.push('--quality', String(opts.quality));
      args.push('--fps', String(fps));
      runHf(args, spanProject.dir);
      // Re-encode for concat safety: setsar=1, no B-frames, strip audio.
      const tmp = span.spanFile + '.tmp.mp4';
      sh('ffmpeg', [
        '-y', '-loglevel', 'error',
        '-i', hfOut,
        '-an',
        '-vf', 'setsar=1',
        '-c:v', 'libx264', '-preset', 'medium', '-crf', '18',
        '-pix_fmt', 'yuv420p', '-g', String(Math.max(1, Math.round(fps))), '-bf', '0',
        '-video_track_timescale', String(Math.round(fps * 1000)),
        tmp,
      ]);
      fs.renameSync(tmp, span.spanFile);
      try { fs.rmSync(hfOut, { force: true }); } catch {}
    }
    return { dir: composed.dir, spans };
  },

  /* Split an already-rendered full MP4 into per-scene video-only spans. Used
   * by the cache fallback path after a full renderer.render(). Encodes with
   * no B-frames for concat-safety. */
  splitSpans(srcMp4, spans, fps, outDir) {
    for (const span of spans) {
      ensureDir(path.dirname(span.spanFile));
      const tmp = span.spanFile + '.tmp.mp4';
      sh('ffmpeg', [
        '-y', '-loglevel', 'error',
        '-i', srcMp4,
        '-ss', String(span.tStart), '-frames:v', String(span.frameCount),
        '-an',
        '-vf', 'setsar=1',
        '-c:v', 'libx264', '-preset', 'medium', '-crf', '18',
        '-pix_fmt', 'yuv420p', '-g', String(Math.max(1, Math.round(fps))), '-bf', '0',
        '-video_track_timescale', String(Math.round(fps * 1000)),
        tmp,
      ]);
      fs.renameSync(tmp, span.spanFile);
    }
  },

  shots(config, outDir, times) {
    const composed = this.compose(config, outDir);
    runHf(['snapshot', '--at', times.join(','), '-o', 'snapshots/review'], composed.dir);
    return { dir: path.join(composed.dir, 'snapshots', 'review'), project: composed.dir };
  },
};

module.exports = provider;
