'use strict';
/* Assembles the composition document. Follows the canonical standalone shape
 * from hyperframes-core/references/minimal-composition.md: root div directly in
 * <body> (no <template>), clips as DIRECT children of the root, audio as a
 * direct root child with framework-owned playback, one synchronous paused GSAP
 * timeline registered under the root's data-composition-id. */
const { runtimeScript } = require('./runtime');

const fmt = n => String(Math.round(n * 1000) / 1000);

function escapeHtml(s) {
  return String(s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

/* Full index.html for the generated project. `data` is composeData() output,
 * `css` the composeCss() stylesheet. */
function composeDoc(config, size, data, css) {
  const title = escapeHtml(config.title || 'narova');
  const nn = String(data.scenes.length).padStart(2, '0');

  const sceneClips = config.scenes.map((s, i) => {
    const sc = data.scenes[i];
    // Keep each track at three scenes or fewer. HyperFrames flags denser tracks
    // as difficult to edit in Studio; scenes never overlap, so banding them is
    // deterministic without changing playback.
    const track = Math.floor(i / 3) + 1;
    return `  <section id="scene-${s.id}" class="clip scene" data-start="${fmt(sc.start)}" data-duration="${fmt(sc.dur)}" data-track-index="${track}">
    <div class="chrome">
      <div class="topbar"><div class="wordmark"><b>${title}</b></div><div class="counter">${String(i + 1).padStart(2, '0')} / ${nn}</div></div>
      <div class="canvas"><div class="scenebody">${s.body}</div></div>
    </div>
  </section>`;
  }).join('\n');

  // JSON inlined into a <script> — escape "<" so "</script>" in a token can't
  // terminate the block early.
  const dataJson = JSON.stringify(data).replace(/</g, '\\u003c');

  return `<!doctype html>
<!-- GENERATED by narova compose — do not edit. Source of truth: reel.config. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=${size.w}, height=${size.h}">
  <title>${title}</title>
  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
  <style>
${css}
  </style>
</head>
<body>
<div id="root" data-composition-id="main" data-start="0"
     data-width="${size.w}" data-height="${size.h}" data-duration="${fmt(data.total)}">
  <div id="bg" class="stage"></div><!-- class="stage" kept so pre-0.3.0 theme.css background rules still apply -->
${sceneClips}
  <section id="overlay" class="clip overlay" data-start="0" data-duration="${fmt(data.total)}" data-track-index="1000">
    <div class="capzone"><div id="cap-stage" style="position:relative;height:100%"></div></div>
    <div class="progress"><i id="progress-bar"></i></div>
  </section>
  <audio id="vo" src="assets/narration.wav" data-start="0" data-track-index="1001"></audio>
</div>
<script>
var DATA = ${dataJson};
${runtimeScript()}
</script>
</body>
</html>
`;
}

module.exports = { composeDoc, escapeHtml };
