'use strict';
/* Assembles the composition document. Follows the canonical standalone shape
 * from hyperframes-core/references/minimal-composition.md: root div directly in
 * <body> (no <template>), clips as DIRECT children of the root, audio as a
 * direct root child with framework-owned playback, one synchronous paused GSAP
 * timeline registered under the root's data-composition-id. */
const { runtimeScript } = require('./runtime');

const fmt = n => String(Math.round(n * 1000) / 1000);

function escapeHtml(s) {
  return String(s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

/* Every scene body lands on ONE page, so a hand-authored global-id rule would
 * make reusable SVG (gradient/filter <defs>, symbols) impossible across
 * scenes. Instead, compose namespaces each body's ids to `<sceneId>--<id>` and
 * rewrites the body's own fragment references to match: url(#…), href="#…",
 * for="…", and aria-labelledby/describedby token lists. Bodies without ids
 * pass through byte-identical. Ids stay unique WITHIN a scene — check.js lints
 * that. */
function namespaceIds(body, sceneId) {
  const src = String(body);
  const ids = [...new Set([...src.matchAll(/(?<![-\w])id\s*=\s*(?:"([^"\s]+)"|'([^'\s]+)')/g)]
    .map(m => m[1] ?? m[2]))];
  if (!ids.length) return src;
  const alt = ids.map(s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  const ns = (m, pre, id, post) => pre + sceneId + '--' + id + post;
  return src
    .replace(new RegExp(`(?<![-\\w])(id\\s*=\\s*["'])(${alt})(["'])`, 'g'), ns)
    .replace(new RegExp(`(url\\(#)(${alt})(\\))`, 'g'), ns)
    .replace(new RegExp(`((?:xlink:)?href\\s*=\\s*["']#)(${alt})(["'])`, 'g'), ns)
    .replace(new RegExp(`(?<![-\\w])(for\\s*=\\s*["'])(${alt})(["'])`, 'g'), ns)
    .replace(/(aria-(?:labelledby|describedby)\s*=\s*["'])([^"']*)(["'])/g,
      (m, pre, val, post) => pre + val.split(/\s+/)
        .map(tok => (ids.includes(tok) ? `${sceneId}--${tok}` : tok)).join(' ') + post);
}

/* Full index.html for the generated project. `data` is composeData() output,
 * `css` the composeCss() stylesheet. */
function composeDoc(config, size, data, css) {
  const title = escapeHtml(config.title || 'narova');
  const nn = String(data.scenes.length).padStart(2, '0');
  // Page furniture is optional. resolveConfig has already turned `chrome:false`
  // into an explicit { topbar:false, counter:false, progress:false } object, so
  // here we only merge that resolved object over the all-on default.
  const chrome = { topbar: true, counter: true, progress: true, ...(config.chrome || {}) };

  const sceneClips = config.scenes.map((s, i) => {
    const sc = data.scenes[i];
    // Keep each track at three scenes or fewer. HyperFrames flags denser tracks
    // as difficult to edit in Studio; scenes never overlap, so banding them is
    // deterministic without changing playback.
    const track = Math.floor(i / 3) + 1;
    const bar = chrome.topbar
      ? `<div class="topbar"><div class="wordmark"><b>${title}</b></div>${
        chrome.counter ? `<div class="counter">${String(i + 1).padStart(2, '0')} / ${nn}</div>` : ''}</div>`
      : '';
    return `  <section id="scene-${s.id}" class="clip scene" data-start="${fmt(sc.start)}" data-duration="${fmt(sc.dur)}" data-track-index="${track}">
    <div class="chrome">
      ${bar}
      <div class="canvas"><div class="scenebody">${namespaceIds(s.body, s.id)}</div></div>
    </div>
  </section>`;
  }).join('\n');

  // JSON inlined into a <script> — escape "<" so "</script>" in a token can't
  // terminate the block early.
  const dataJson = JSON.stringify(data).replace(/</g, '\\u003c');

  return `<!doctype html>
<!-- GENERATED by narova compose — do not edit. Source of truth: reel.config. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=${size.w}, height=${size.h}">
  <title>${title}</title>
  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
  <style>
${css}
  </style>
</head>
<body>
<div id="root" data-composition-id="main" data-start="0"
     data-width="${size.w}" data-height="${size.h}" data-duration="${fmt(data.total)}">
  <div id="bg" class="stage"></div><!-- class="stage" kept so pre-0.3.0 theme.css background rules still apply -->
${sceneClips}
  <section id="overlay" class="clip overlay" data-start="0" data-duration="${fmt(data.total)}" data-track-index="1000">
    <div class="capzone"><div id="cap-stage" style="position:relative;height:100%"></div></div>
    ${chrome.progress ? '<div class="progress"><i id="progress-bar"></i></div>' : ''}
  </section>
  <audio id="vo" src="assets/narration.wav" data-start="0" data-track-index="1001"></audio>
</div>
<script>
var DATA = ${dataJson};
${runtimeScript()}
</script>
</body>
</html>
`;
}

module.exports = { composeDoc, escapeHtml, namespaceIds };
